import sys
import radia as rad
from numpy import *

mu0 = 4*pi*1e-7
Br=0.85#残留磁束密度
Hcb=660#保磁力(kA/m)
Hcj=1194#保磁力(kA/m)

g = rad.ObjBckg([0,0,1])
Bz = rad.Fld(g,"Bz",[0, 0, 0])
print(Bz)


def BuildGeometry():
	#Current Densities in A/mm^2
	j1 = 128; j2 = 256

	#Coil Presentation Parameters
	n1 = 3; n2 = 6; c2 = [1,0,0]; c1 = [0,1,1]; thcn = 0.001

	#Create 5 Coils
	Rt1 = rad.ObjRaceTrk([0.,0.,38.], [9.5,24.5], [120.,0.], 36, n1, j1)
	rad.ObjDrwAtr(Rt1, c1, thcn)
	Rt3 = rad.ObjRaceTrk([0.,0.,76.], [10.,25.], [90.,0.], 24, n1, j1)
	rad.ObjDrwAtr(Rt3, c1, thcn)
	Rt2 = rad.ObjRaceTrk([0.,0.,38.], [24.5,55.5], [120.,0.], 36, n1, j2)
	rad.ObjDrwAtr(Rt2, c2, thcn)
	Rt4 = rad.ObjRaceTrk([0.,0.,76.], [25.,55.], [90.,0.], 24, n1, j2)
	rad.ObjDrwAtr(Rt4, c2, thcn)
	Rt5 = rad.ObjRaceTrk([0.,0.,60.], [150.,166.3], [0.,0.], 39, n2, -j2)
	rad.ObjDrwAtr(Rt5, c2, thcn)

	Grp = rad.ObjCnt([Rt1, Rt2, Rt3, Rt4, Rt5])

	#Define Mirror Coils
	rad.TrfZerPara(Grp, [0,0,0], [0,0,1])

	return Grp

g = BuildGeometry()
rad.ObjDrwOpenGL(g)

'''

#g21 = rad.ObjRecMag([-2.5,-2.5,-10],[5, 5, 20],[0,0,0])
#g22 = rad.ObjRecMag([-2.5, 2.5,-10],[5, 5, 20],[0,0,0])
#g23 = rad.ObjRecMag([ 2.5, 2.5,-10],[5, 5, 20],[0,0,0])
#g24 = rad.ObjRecMag([ 2.5,-2.5,-10],[5, 5, 20],[0,0,0])
#g2 = rad.ObjCnt([g21, g22, g23, g24])

g2 = rad.ObjRecMag([ 0, 0,-10],[10, 10, 20],[0,0,0])
m2 = rad.MatLin([9999,9999], [0,0,1])
rad.MatApl(g2,m2)

g = rad.ObjCnt([g1, g2])

print(f"DOF = {rad.ObjDegFre(g)}")
res=rad.Solve(g, 0.00001,100)
print(res)

x1 = 0
y1 = 0
z1 = 0
x2 = 0
y2 = 0
z2 = 10
np = 10

Bx = rad.FldLst(g,"Bx", [x1,y1,z1], [x2,y2,z2], np, "noarg")
print(Bx)
print(type(Bx))

sys.exit()

exportGeometryToVTK(g, 'RADIA')

Nx = 31
Ny = 31
Nz = 31
x = linspace(-30,30,Nx)
y = linspace(-30,30,Ny)
z = linspace(-30,30,Nz)
dx = (x[1]-x[0])
dy = (y[1]-y[0])
dz = (z[1]-z[0])
with open('MagneticFluxDensity.vtk','w') as fid:
	fid.write(f'# vtk DataFile Version 2.0\n')
	fid.write(f'Generated by ksugahar\n')
	fid.write(f'ASCII\n')
	fid.write(f'DATASET STRUCTURED_POINTS\n')
	fid.write(f'DIMENSIONS {Nx} {Ny} {Nz}\n')
	fid.write(f'ORIGIN {x[0]} {y[0]} {z[0]}\n')
	fid.write(f'SPACING {dx} {dy} {dz}\n')
	fid.write(f'POINT_DATA {Nx*Ny*Nz}\n')
	fid.write(f'SCALARS B_magnitude float\n')
	fid.write(f'LOOKUP_TABLE default\n')
	for nz in range(Nz):
		for ny in range(Ny):
			for nx in range(Nx):
				bx = rad.Fld(g,"Bx",[x[nx],y[ny],z[nz]])
				by = rad.Fld(g,"By",[x[nx],y[ny],z[nz]])
				bz = rad.Fld(g,"Bz",[x[nx],y[ny],z[nz]])
				b = sqrt(bx**2+by**2+bz**2)
				fid.write(f'{b}\n');
	fid.write(f'VECTORS B_vectors float\n')
	for nz in range(Nz):
		for ny in range(Ny):
			for nx in range(Nx):
				bx = rad.Fld(g,"Bx",[x[nx],y[ny],z[nz]])
				by = rad.Fld(g,"By",[x[nx],y[ny],z[nz]])
				bz = rad.Fld(g,"Bz",[x[nx],y[ny],z[nz]])
				fid.write(f'{bx} {by} {bz}\n');
	fid.close()
print("end")
'''