import os, sys
import radia as rad
from numpy import *
from my_module import *

import matplotlib.pyplot as plt
sys.path.append("C:/Program Files/Coreform Cubit 2023.11/bin")
import cubit

def ObjCylin(R, H, M, N, x0, y0, z0, ks1, ks2, mrx, mry, mrz):
	t = linspace(0,2*pi,N+1)
	t = t[0:-1]
	x1 = R*cos(t)+x0
	y1 = R*sin(t)+y0
	z1 =-H/2*ones(size(t))+z0
	z2 = H/2*ones(size(t))+z0
	points = transpose(vstack((vstack((hstack((x1,x1)),hstack((y1,y1)))),hstack((z1,z2)))))
	face = [list(range(1,N+1)),list(range(N+1,2*N+1))]
	for n in range(1,N):
		face.append([n,n+1,n+1+N,n+N])
	face.append([N,1,1+N,2*N])
	g = rad.ObjPolyhdr(points.tolist(),face,M)
	mat = rad.MatLin([ks1,ks2], [mrx,mry,mrz])#ks1:水平方向の磁化率、ks2:垂直方向の磁化率、mrx,mry,mrz:残留磁化ベクトル(T)
	rad.MatApl(g, mat)                        #磁化率x=比透磁率ur-1
	g = rad.ObjDivMag(g,n1)
	return g

meshsize = 1
ironcolor=[0,0.5,1]
magcolor=[1,0,0]
mag2color=[0,1,1]
mu0 = 4*pi*1e-7
Br=1.03#残留磁束密度
Hcb=756#保磁力(kA/m)
Hcj=1433#保磁力(kA/m)
R = 60
H = 20
H2 = H
H3 = -H
magR = 5#サマコバ磁石の半径
magH = 5#サマコバ磁石の高さ
dX = 12

cubit.init(["cubit","-nojournal"])
cubit.cmd('reset')
cubit.cmd('create Cylinder height {} radius {}'.format(H, R))
cubit.cmd('create Cylinder height {} radius {}'.format(H, R))
cubit.cmd('move Volume 1 z {} include_merged '.format(H2))
cubit.cmd('move Volume 2 z {} include_merged '.format(H3))

"""
i=3
for nx in range(-20,21):
	for ny in range(-20,21):
		x = nx*dX + mod(ny,2)*dX/2
		y = ny*dX*sqrt(3)/2
		z = H/2+magH/2+H2+1
		if (x**2+y**2)<(R-magR/2)**2:
			cubit.cmd('create Cylinder height {} radius {}'.format(magH, magR))
			cubit.cmd('move Volume {} x {} y {} z {} include_merged '.format(i,x,y,z))
			print(i)
			i = i+1
"""
#cubit.cmd('create Cylinder height 10 radius 5')
#cubit.cmd('move Volume 2 z 15 include_merged ')
#cubit.cmd('webcut volume all with plane zplane offset 10 ')
cubit.cmd('mearge all')
cubit.cmd('imprint all')
cubit.cmd('volume all size {meshsize}')
cubit.cmd('mesh volume all')
cubit.cmd('block 1 add vol 1')
cubit.cmd('block 1 name "iron"')
cubit.cmd('block 2 add vol 2')
cubit.cmd('block 2 name "iron2"')
"""
for num in range(3,i):
	cubit.cmd('block {} add vol {}'.format(num,num))
"""
n1 = [2,2,2]
for block_id in cubit.get_block_id_list():
	name = cubit.get_exodus_entity_name("block",block_id)
	#print(f'block name = "{name}"')
	volume_list = cubit.get_block_volumes(block_id)
	for volume_id in volume_list:
		hex_list = cubit.get_volume_hexes(volume_id)
		if len(hex_list)>0:
			#print(f'number of hexahedron = {len(hex_list)}')
			for hex_id in hex_list:
				connectivity_list = cubit.get_connectivity("hex", hex_id)
				coords = []
				for node_id in connectivity_list:
					coord = cubit.get_nodal_coordinates(node_id)
					coords.append(list(coord))

				N=24
				face = [[1,2,3,4],[1,5,6,2],[2,6,7,3],[3,7,8,4],[1,4,8,5],[5,8,7,6]]
				if block_id == 1:
					M = [0,0,0.41]
					g_ = rad.ObjPolyhdr(coords,face,M)
					if "g1" in locals():
						g1 = rad.ObjCnt([g1, g_])
						rad.ObjDrwAtr(g1,ironcolor)
					else:
						g1 = g_ 		
				if block_id == 2:
					M = [0,0,0]
					g_ = rad.ObjPolyhdr(coords,face,M)
					if "g2" in locals():
						g2 = rad.ObjCnt([g2, g_])
						rad.ObjDrwAtr(g2,ironcolor)
					else:
						g2 = g_
				"""
				if 3<= block_id <= i:
					M = [0,0,1]
					g_ = rad.ObjPolyhdr(coords,face,M)
					if "g{}".format(block_id) in locals():
						exec("g{} = rad.ObjCnt([g{}, g_])".format(block_id,block_id))
						exec("rad.ObjDrwAtr(g{},ironcolor)".format(block_id))
					else:
						exec("g{} = g_".format(block_id))
				""" 
mat_iron = rad.MatLin([9999,9999], [0,0,100])#ks1:水平方向の磁化率、ks2:垂直方向の磁化率、mrx,mry,mrz:残留磁化ベクトル(T)
rad.MatApl(g1, mat_iron)
rad.MatApl(g2, mat_iron) 

g = rad.ObjCnt([g1, g2])
magM = [0,0,Br]
for nx in range(-20,21):
	for ny in range(-20,21):
		x = nx*dX + mod(ny,2)*dX/2
		y = ny*dX*sqrt(3)/2
		z = H/2 + magH/2+20
		if (x**2+y**2)<(R-magR/2)**2:
			g_ = ObjCylin(magR, magH, magM, N, x, y, z, 0.14, 0.14, 0, 0, 1)
			rad.ObjDrwAtr(g_,magcolor)
			g = rad.ObjCnt([g, g_])

for nx in range(-20,21):
	for ny in range(-20,21):
		x = nx*dX + mod(ny,2)*dX/2
		y = ny*dX*sqrt(3)/2
		z = -H/2 - magH/2-20
		if (x**2+y**2)<(R-magR/2)**2:
			g_ = ObjCylin(magR, magH, magM, N, x, y, z, 0.14, 0.14, 0, 0, 1)
			rad.ObjDrwAtr(g_,magcolor)
			g = rad.ObjCnt([g, g_])
"""
for id in range(3,i):
	#g = rad.ObjCnt([g, "g{}".format(id)])
	exec("g = rad.ObjCnt([g, g{}])".format(id))
"""
rad.ObjDrwOpenGL(g)

print(f"DOF = {rad.ObjDegFre(g)}")
res=rad.Solve(g, 0.00001,100)
print(res)
print("end")
"""
exportGeometryToVTK(g, 'kondomodel_cubit')

Nx = 31
Ny = 31
Nz = 31
x = linspace(-150,150,Nx)
y = linspace(-150,150,Ny)
z = linspace(-150,150,Nz)
dx = (x[1]-x[0])
dy = (y[1]-y[0])
dz = (z[1]-z[0])

with open('MagneticFluxDensity_kondomodel_cubit.vtk','w') as fid:
	fid.write(f'# vtk DataFile Version 2.0\n')
	fid.write(f'Generated by ksugahar\n')
	fid.write(f'ASCII\n')
	fid.write(f'DATASET STRUCTURED_POINTS\n')
	fid.write(f'DIMENSIONS {Nx} {Ny} {Nz}\n')
	fid.write(f'ORIGIN {x[0]} {y[0]} {z[0]}\n')
	fid.write(f'SPACING {dx} {dy} {dz}\n')
	fid.write(f'POINT_DATA {Nx*Ny*Nz}\n')
	fid.write(f'SCALARS B_magnitude float\n')
	fid.write(f'LOOKUP_TABLE default\n')
	for nz in range(Nz):
		for ny in range(Ny):
			for nx in range(Nx):
				bx = rad.Fld(g,"Bx",[x[nx],y[ny],z[nz]])
				by = rad.Fld(g,"By",[x[nx],y[ny],z[nz]])
				bz = rad.Fld(g,"Bz",[x[nx],y[ny],z[nz]])
				b = sqrt(bx**2+by**2+bz**2)
				fid.write(f'{b}\n')
	fid.write(f'VECTORS B_vectors float\n')
	for nz in range(Nz):
		for ny in range(Ny):
			for nx in range(Nx):
				bx = rad.Fld(g,"Bx",[x[nx],y[ny],z[nz]])
				by = rad.Fld(g,"By",[x[nx],y[ny],z[nz]])
				bz = rad.Fld(g,"Bz",[x[nx],y[ny],z[nz]])
				fid.write(f'{bx} {by} {bz}\n')
	fid.close()

print("end")

bbx = []
bby = []
bbz = []
bb = []
NN = 1500
x2 = linspace(-150,150,NN)
for nx in range(NN):
	bx2 = rad.Fld(g,"Bx",[x2[nx],0,0])
	by2 = rad.Fld(g,"By",[x2[nx],0,0])
	bz2 = rad.Fld(g,"Bz",[x2[nx],0,0])
	b2 = sqrt(bx2**2+by2**2+bz2**2)
	bb.append(b2)
	bbx.append(bx2)
	bby.append(by2)
	bbz.append(bz2)

plt.plot(x2,bb)
plt.show()

len = len(x2)

csvpath = "kondomodel_cubit.csv"
with open(csvpath, "w", encoding="utf_8_sig") as f:
    writer = csv.writer(f, lineterminator='\n')
    for i in range(0,len):
        writer.writerow([x2[i],bb[i],bbx[i],bby[i],bbz[i]])
print("end2")
"""