import sys
import radia as rad
from numpy import *
from my_module import *

mu0 = 4*pi*1e-7
Br=0.85#残留磁束密度
Hcb=660#保磁力(kA/m)
Hcj=1194#保磁力(kA/m)


g1 = rad.ObjRecMag([0,0,  5],[10,10,10],[0,0,1])
g2 = rad.ObjRecMag([ 0, 0,-10],[10, 10, 20],[0,0,0])
m2 = rad.MatLin([9999,9999], [0,0,1])
rad.MatApl(g2,m2)

g = rad.ObjCnt([g1, g2])

print(f"DOF = {rad.ObjDegFre(g)}")
res=rad.Solve(g, 0.00001,100)
print(res)

exportGeometryToVTK(g, 'RADIA')

Nx = 31
Ny = 31
Nz = 31
x = linspace(-30,30,Nx)
y = linspace(-30,30,Ny)
z = linspace(-30,30,Nz)
dx = (x[1]-x[0])
dy = (y[1]-y[0])
dz = (z[1]-z[0])
with open('MagneticFluxDensity.vtk','w') as fid:
	fid.write(f'# vtk DataFile Version 2.0\n')
	fid.write(f'Generated by ksugahar\n')
	fid.write(f'ASCII\n')
	fid.write(f'DATASET STRUCTURED_POINTS\n')
	fid.write(f'DIMENSIONS {Nx} {Ny} {Nz}\n')
	fid.write(f'ORIGIN {x[0]} {y[0]} {z[0]}\n')
	fid.write(f'SPACING {dx} {dy} {dz}\n')
	fid.write(f'POINT_DATA {Nx*Ny*Nz}\n')
	fid.write(f'SCALARS B_magnitude float\n')
	fid.write(f'LOOKUP_TABLE default\n')
	for nz in range(Nz):
		for ny in range(Ny):
			for nx in range(Nx):
				bx = rad.Fld(g,"Bx",[x[nx],y[ny],z[nz]])
				by = rad.Fld(g,"By",[x[nx],y[ny],z[nz]])
				bz = rad.Fld(g,"Bz",[x[nx],y[ny],z[nz]])
				b = sqrt(bx**2+by**2+bz**2)
				fid.write(f'{b}\n');
	fid.write(f'VECTORS B_vectors float\n')
	for nz in range(Nz):
		for ny in range(Ny):
			for nx in range(Nx):
				bx = rad.Fld(g,"Bx",[x[nx],y[ny],z[nz]])
				by = rad.Fld(g,"By",[x[nx],y[ny],z[nz]])
				bz = rad.Fld(g,"Bz",[x[nx],y[ny],z[nz]])
				fid.write(f'{bx} {by} {bz}\n');
	fid.close()

print("end")
